format_version: 10
pipelines:
  Dev:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-48e63a1:
        git: git@github.com-anoopelias-tw:anoopelias-tw/tw-bootcamp-01-measurement.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test
                command: ./gradlew
                run_if: passed
    - Build:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build:
            timeout: 0
            artifacts:
            - build:
                source: tw-bootcamp-measurement-1.0-SNAPSHOT.jar
                destination: build
            tasks:
            - exec:
                arguments:
                - '"Build"'
                command: echo
                run_if: passed
          package:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build
                command: ./gradlew
                run_if: passed
            - exec:
                arguments:
                - -al build/libs/
                command: ls
                run_if: passed
