format_version: 10
pipelines:
  Dev:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-48e63a1:
        git: git@github.com-anoopelias-tw:anoopelias-tw/tw-bootcamp-01-measurement.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test
                command: ./gradlew
                run_if: passed
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '"Build"'
                command: echo
                run_if: passed
          package:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '"Package"'
                command: echo
                run_if: passed
            - exec:
                arguments:
                - '"Package stage 2"'
                command: echo
                run_if: passed
  QA:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      Dev:
        ignore_for_scheduling: false
        pipeline: Dev
        stage: Test
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '" Test in QA pipeline"'
                command: echo
                run_if: passed
    - Deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '"Deploy to QA"'
                command: echo
                run_if: passed
