format_version: 10
pipelines:
  hotfix:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-repo:
        git: git@github.com-anoopelias-tw:anoopelias-tw/tw-bootcamp-01-measurement.git
        shallow_clone: false
        auto_update: false
        branch: main
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test
                command: ./gradlew
                run_if: passed
    - build:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          package:
            timeout: 0
            artifacts:
            - build:
                source: build/libs/tw-bootcamp-measurement-1.0-SNAPSHOT.jar
                destination: build
            tasks:
            - exec:
                arguments:
                - build
                command: ./gradlew
                run_if: passed
