format_version: 10
pipelines:
  QA:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      dev:
        ignore_for_scheduling: false
        pipeline: Dev
        stage: build
    stages:
    - Deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy:
            timeout: 0
            tasks:
            - fetch:
                is_file: true
                source: build/tw-bootcamp-measurement-1.0-SNAPSHOT.jar
                destination: ''
                pipeline: Dev
                stage: build
                job: package
                artifact_origin: gocd
                run_if: passed
            - exec:
                arguments:
                  - Fetch complete
                command: echo
                run_if: passed
            - exec:
                arguments:
                  - -al
                command: ls
                run_if: passed
            - exec:
                arguments:
                - '"Deploy to QA"'
                command: echo
                run_if: passed
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '"Test in QA pipeline"'
                command: echo
                run_if: passed
