format_version: 10
pipelines:
  UAT:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      QA:
        ignore_for_scheduling: false
        pipeline: QA
        stage: Test
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '" Test in UAT pipeline"'
                command: echo
                run_if: passed
    - Deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Deploy:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '"Deploy to UAT"'
                command: echo
                run_if: passed
