on:
  workflow_run:
    types:
      - completed
    workflows:
      - UAT

name: QA
run-name: QA stage

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy_prod"

  sanity_prod:
    runs-on: ubuntu-latest
    needs: deploy_prod
    steps:
      - run: echo "sanity_prod"